# Generated by Django 3.1.7 on 2021-03-24 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_uri', models.CharField(default='', max_length=255)),
                ('callback_secret', models.CharField(default='', max_length=255)),
                ('callback_id', models.CharField(default='', max_length=255)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.channel')),
            ],
        ),
    ]
