# Generated by Django 3.1.7 on 2021-04-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='channel',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
