# Generated by Django 3.1.7 on 2021-04-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='welcome_msg',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
