# Generated by Django 3.1.7 on 2021-04-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_channel_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
