# Generated by Django 3.1.7 on 2021-04-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_channel_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='viewers',
        ),
    ]
