# Generated by Django 3.1.7 on 2021-04-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_channel_websocket_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='websocket_url',
        ),
    ]
